### ISSUE TITLE
[BUG] Spotify is closing the SpotifyAB

### ISSUE THREAD

**Issue by rxlxtxvxst** [An0n-00/SpotifyAB#15]
**Describe the bug**
I open SpotifyAB. I open Spotify, but won't run. I check Spotify AB and it says Spotify closed to avoid conflicts. See screenshots. My Spotify is not downloaded from Microsoft Store and I do have the app in my desktop, yet still not working. :( 

**Expected behavior**

I expected how dev  described what will happen, Spotify would seamlessly run and play music without ads.

**Screenshots**

![Image](https://github.com/user-attachments/assets/d2f83a6b-5240-4c56-aeec-c5aa285c5168)

**Desktop (please complete the following information):**

- OS: Windows 10

- SpotifyAB Version: 1.0.0.0

- Spotify Version: 1.2.59.514

**Additional context**

**Comment by An0n-00** [comment]
Hey @rxlxtxvxst thanks for your issue. I will investigate this today (in the next 12h). I have a hunch on what the issue might be. Please bare with me. (Until then, please "uninstall spotifyAB" from Spotify, so that it doesn't conflict with the update that I will publish later.)

Thanks. 
An0n-00

**Comment by rxlxtxvxst** [comment]
No problem at all. Noting the uninstallation. Thanks @An0n-00.

**Comment by An0n-00** [comment]
ahem, theoretically this is not really a bug.... if you have spotify installed (the spotify NOT from the ms store), you should open spotify AB --> press install spotifyAB --> close the spotify AB Client and then listen to the music without ads... 

I [added a protection](https://github.com/An0n-00/SpotifyAB/blob/main/SpotifyABClient/Dashboard.cs#L26) against opening spotify while spotifyAB is running, since that might cause some interference with the processes.. 


If you installed spotify AB to spotify, you can close the spotifyAB client and then just run spotify... does that work?

**Comment by An0n-00** [comment]
Just that you know... I also updated the ad block mechanism to the latest spotify version, so that should also be fixed. 

Everything should be working as planned... If it does not, I recommend uninstalling spotifyAB from spotify if you did not do that already, and then uninstall spotify, and then install the newest spotify version [direct link](https://download.scdn.co/SpotifySetup.exe) and then click install spotifyAB in the client again. I just did that and it worked👍

If it does not, please write a new comment here and I will try to help you as good as I can. (until then i think this "issue" is closed👍)

**Comment by rxlxtxvxst** [comment]
Hi @An0n-00, thank you for this. Unfortunately, I'm still having issues.

I tried reinstalling Spotify from the directlink you sent and added the xpui file from the repository but Ihe SpoitiyAB is still not recognizing spotify and unable to install Spotify AB into my spotify.

![Image](https://github.com/user-attachments/assets/beec89fe-184b-4f23-984f-944121620cf3)

![Image](https://github.com/user-attachments/assets/fe3347b6-8f19-4f1c-9f5d-25fbd29f3212)

![Image](https://github.com/user-attachments/assets/f8758aed-053b-4705-8568-68ffe586368c)

**Comment by An0n-00** [comment]
hmm.. interesting.. so spotifyAB (the client) thinks you do NOT have spotify installed even though you do? 

ahem if you downloaded the xpui.spa file and replaced it manually it should block ads.... (you do not need spotifyAB running)

**Comment by rxlxtxvxst** [comment]
Yeah, the client is saying I don't. As seen from the screenshot. 

Oh! I'll try to play Spotify throughout the day and see if ads are still playing. I'll update later. 

Thanks, @An0n-00 .

**Comment by An0n-00** [comment]
(just that you know... it will say that spotify is broken if it cannot find the appdata\Spotify\Apps\xpui.spa file)

**Comment by rxlxtxvxst** [comment]
Hello again @An0n-00. I think I had lesser ads when I used it for half day. I had 5 ads. 

This is where my xpui.spa file is. Should it be somewhere different?
![Image](https://github.com/user-attachments/assets/cc91c08b-c9d8-401d-b77e-3f3221fb8a21)

**Comment by An0n-00** [comment]
okay... well yes the visual ads (like banners on the home screen) should not be there anymore, if the versions do not match, you will hear audio ads though...  

what spotify version are you on now?🤔

**Comment by rxlxtxvxst** [comment]
Banners are no longer visible, but I still have the audio ones - the 5 ones.

Here's my Spotify version. 

![Image](https://github.com/user-attachments/assets/a6c79d45-47d2-49bc-948d-ca7f03b44961)

**Comment by An0n-00** [comment]
okay yeah i am a little cooked ( i think i know what the problem is, but i am thinking rn if i should even keep this project running.....)

I recommend using spot x: https://github.com/SpotX-Official/SpotX

(i will decommission this project😔)
